import { EntitySchema } from 'typeorm';

export const TokenTwitterEntity = new EntitySchema({
  name: 'token_twitter',
  tableName: 'token_twitter',
  columns: {
    token_id: { type: 'bigint', primary: true },
    handle: { type: 'text' },
    user_id: { type: 'text', nullable: true },
    profile_url: { type: 'text', nullable: true },
    name: { type: 'text', nullable: true },
    is_blue_verified: { type: 'boolean', nullable: true },
    verified_type: { type: 'text', nullable: true },
    profile_picture: { type: 'text', nullable: true },
    cover_picture: { type: 'text', nullable: true },
    description: { type: 'text', nullable: true },
    location: { type: 'text', nullable: true },
    followers: { type: 'bigint', nullable: true },
    following: { type: 'bigint', nullable: true },
    favourites_count: { type: 'bigint', nullable: true },
    statuses_count: { type: 'bigint', nullable: true },
    media_count: { type: 'bigint', nullable: true },
    can_dm: { type: 'boolean', nullable: true },
    created_at_twitter: { type: 'timestamptz', nullable: true },
    possibly_sensitive: { type: 'boolean', nullable: true },
    is_automated: { type: 'boolean', nullable: true },
    automated_by: { type: 'text', nullable: true },
    pinned_tweet_ids: { type: 'text', array: true, nullable: true },
    unavailable: { type: 'boolean', nullable: true },
    unavailable_message: { type: 'text', nullable: true },
    unavailable_reason: { type: 'text', nullable: true },
    raw: { type: 'jsonb', nullable: true },
    last_refreshed: { type: 'timestamptz', default: () => 'now()' },
    last_error: { type: 'text', nullable: true },
    last_error_at: { type: 'timestamptz', nullable: true },
  },
  indices: [
    { name: 'idx_token_twitter_handle', columns: ['handle'] },
    { name: 'idx_token_twitter_last_refreshed', columns: ['last_refreshed'] },
  ],
});
